#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in2,    LiftPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    ClawPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  RBaseEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl3,  LBaseEnc,       sensorQuadEncoder)
#pragma config(Motor,  port2,           RFBase,        tmotorVex393_MC29, openLoop, driveRight, encoderPort, dgtl1)
#pragma config(Motor,  port3,           RBBase,        tmotorVex393_MC29, openLoop, driveLeft, encoderPort, dgtl3)
#pragma config(Motor,  port4,           Lift,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Claw,          tmotorServoStandard, openLoop)
#pragma config(Motor,  port6,           LFBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           LBBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           Cone,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Mogo,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

/**************************
BUILD DATE: 	4/8/16
AUTHOR: 			JAIVEER SINGH
V5.3.2
**************************/

//VRC Specific pragmas below
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Includes/Vex_Competition_Includes-.h"
//VRC Specific pragmas above

#include "Joystick_Defs.h" 	//Define joystick buttons in more user-friendly terms
#include "Constants.h" 			//All constants used in the entire program
#include "TrueSpeed_Slew.h" //Advanced motor control for the robot
#include "Base.h"						//All base-control code
#include "Intake.h" 				//All intake-control code
#include "Lift.h" 					//All lift-control code
#include "LCD.h"						//All LCD code

/*
Function that starts tasks that need to always be on.
Has no inputs or outputs.
*/
void startAlwaysTasks()
{
	startTask(LCD);
	startTask(baseSlewControl);
	startTask(liftSlewControl);
}

void startDriverTasks()
{
	startTask(base);
	startTask(lift);
	startTask(intake);
	//startTask(mogo);
}

//Ready for match after reconnect
void pre_auton()
{
	startAlwaysTasks();
	//By slaving motors together, they can never accidentally drive in opposite directions
	slaveMotor(RBBase, RFBase);
	slaveMotor(LBBase, LFBase);
}

bool auton_flag = false;

task autonomous()
{
	//LeftC3S2x();
	motor[RFBase] = 127;
	motor[LFBase] = 127;
	wait1Msec(5000);
	motor[RFBase] = 0;
	motor[LFBase] = 0;
	auton_flag = true;
}

task usercontrol()
{
	startAlwaysTasks();	//Just in case comp control has turned them off
	startDriverTasks();	//Activate everything for driver
	while(true)
	{
		EndTimeSlice();
	}
}
