#pragma config(UART_Usage, UART1, uartVEXLCD, baudRate19200, IOPins, None, None)
#pragma config(UART_Usage, UART2, uartNotUsed, baudRate4800, IOPins, None, None)
#pragma config(Sensor, in1,    VbarPot,        sensorPotentiometer)
#pragma config(Sensor, in2,    LiftPot,        sensorPotentiometer)
#pragma config(Sensor, in3,    MogoPot,        sensorPotentiometer)
#pragma config(Sensor, dgtl1,  LBaseEnc,       sensorQuadEncoder)
#pragma config(Sensor, dgtl11, RBaseEnc,       sensorQuadEncoder)
#pragma config(Motor,  port2,           LFBase,        tmotorVex393_MC29, openLoop, driveRight, encoderPort, dgtl1)
#pragma config(Motor,  port3,           RFBase,        tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port4,           LiftM,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           VbarM,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           LMBBase,       tmotorVex393_MC29, openLoop, driveRight, encoderPort, None)
#pragma config(Motor,  port7,           RMBBase,       tmotorVex393_MC29, openLoop, driveLeft)
#pragma config(Motor,  port8,           MogoM,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ClawM,         tmotorVex393_MC29, openLoop, reversed)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//VRC-specific pragmas below
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"
//VRC-specific pragmas above

//BCI library includes below
#define BCI_USE_LCDCONTROL
#define BCI_USE_MOTORCONTROL
#define BCI_USE_POS_PID
#define MENU_NUM 4
#define sm(m, sp) setMotorSpeed(m, sp)
#include "Libraries\BCI-master\BCI.h"
//BCI library includes above

//Custom includes below
#include "Includes/Constants.h"
#include "Includes/JoystickDefs.h"
#include "Includes/Base.h"
#include "Includes/Lift.h"
#include "Includes/Claw.h"
#include "Includes/Mogo.h"
#include "Includes/Vertibar.h"
#include "Includes/LCD.h"
#include "Includes/AutonRoutines.h"
//Custom includes above

void pre_auton()
{
	configBase();
	configLCD();
	bStopTasksBetweenModes = false;
}

task autonomous()
{
	startTask(autonLiftTask);
	startTask(autonVbarTask);
	startTask(autonClawTask);
	startTask(autonMogoTask);
}

task usercontrol()
{
	startTask(driverBaseTask);
	startTask(driverLiftTask);
	startTask(driverVbarTask);
	startTask(driverClawTask);
	startTask(driverMogoTask);
	while(true)
	{
		EndTimeSlice();
	}
}
