#pragma config(Sensor, in1,    BallSensor,     sensorReflection)
#pragma config(Sensor, in2,    AnglePot1,      sensorPotentiometer)
#pragma config(Sensor, in3,    AnglePot2,      sensorPotentiometer)
#pragma config(Sensor, in4,    Turnstile,      sensorNone)
#pragma config(Sensor, in8,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  LauncherSet,    sensorTouch)
#pragma config(Sensor, dgtl2,  AngleSet,       sensorTouch)
#pragma config(Sensor, dgtl3,  Green1,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  Green2,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  Green3,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  Red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  BallFinder1,    sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  BallFinder2,    sensorSONAR_cm)
#pragma config(Motor,  port1,           Intake,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Out1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port3,           RFBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port4,           LFBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Angle,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           Out2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           RBBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LBBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           Out3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Elevator,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//VRC Specific pragmas below
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"
//VRC Specific pragmas above

#define X_Joy vexRT[Ch4]
#define Y_Joy vexRT[Ch3]
#define rot_Joy vexRT[Ch1]
#define intakeBtn vexRT[Btn6D]
#define outtakeBtn vexRT[Btn5D]
#define elevateBtn vexRT[Btn6U]
#define delevatebtn vexRT[Btn5D]
#define launchBtn vexRT[Btn8R]
#define launchAdjBk vexRT[Btn8L]
#define angleUpBtn vexRT[Btn7U]
#define angleDownBtn vexRT[Btn7D]
#define angleLongBtn vexRT[Btn8U]
#define angleShortBtn vexRT[Btn8D]
#define overrideBtn vexRT[Btn7L]

int Ball_Count = 0;

int Auton_Drive_Array[4]; //Arrays that are used during autonomous in a manner similar to the motor array, contains: X, Y, Rot, and Duration
int Auton_Aim_Array[2]; //Contains: Absolute and Adjust
int Auton_Launch_Array[2]; //Contains: Ball Count and Adjust
int Auton_Intake_Array[1]; //Contains: Direction

#include "CONSTANTS.h"
#include "General_Functions.h"
#include "Robot_Functions.h"
#include "Always_Tasks.h"
#include "Autonomous_Tasks.h"
#include "DriverControl_Tasks.h"

#define pew LauncherControl(1)
//Predefined construct
void pre_auton()
{
	bStopTasksBetweenModes = true;
	SensorType[in4] = sensorNone; //Reset gyroscope at beginning of program
	wait1Msec(1000);
	SensorType[in4] = sensorGyro;
	wait1Msec(2000);
}

//Predefined construct
task autonomous
{
	startTask(Auton_Drive); //Start necessary tasks
	startTask(Auton_Intaking);
	startTask(Auton_Launch);
	startTask(Auton_Aim);
	Always(); //Start tasks that should be always run
	pew; //Shoot 4 times, launching the auton preloads
	pew;
	pew;
	pew;
	ABase(0, 100, 0, 250); //Move the robot slightly forward, so that there is enough clearance for the robot to turn
	ABase(0, 0, 100, 500); //Rotate the robot 135 degrees clockwise, so that we are now facing the near wall
	ABase(0, 100, 0, 250); //Ram into the wall for angle alignment
	ABase(0, -100, 0, 250); //Move back slightly so that we can strafe over without knocking over the pile of balls

	int defaultUltraSensing = getUltras(); //Define an initial value and strafe over until we detect balls
	repeatUntil(getUltras() < defaultUltraSensing - BALL_WIDTH)
	{
		ABase(-100, 0, 0, 50);
	}
	AIntake(1); //Turn intake on
	ABase(0, 100, 0, 500); //Move forward with intake still on
	ABase(0, 0, 0, 10); //Reset base once balls have been intaken
	AIntake(0); //Turn intake off
	ABase(0, -100, 0, 500); //Back up to prepare for shooting
	ABase(0, 0, -100, 250); //Aim at high goal
	pew; //Shoot the four balls from first pyramid
	pew;
	pew;
	pew;
	AIntake(1); //Turn the intake on
	ABase(0, 100, 0, 750); //Drive forward and intake second pyramid
	ABase(0, 0, 0, 500); //Reset base and wait while last balls are intook
	AIntake(0); //Turn intake off
}
//Predefined construct
task usercontrol()
{
	Always();
	startTask(Drive);
	startTask(Intaking);
	startTask(Launch);
	startTask(Aim);
	startTask(EmergencyOverride);
	while (true)
	{
		EndTimeSlice();
	}
}
