#pragma config(Sensor, in1,    AnglePot,       sensorPotentiometer)
#pragma config(Sensor, in2,    BallSensorLauncher, sensorLineFollower)
#pragma config(Sensor, in3,    BallSensor1,    sensorReflection)
#pragma config(Sensor, in4,    BallSensor2,    sensorReflection)
#pragma config(Sensor, in5,    BallSensor3,    sensorReflection)
#pragma config(Sensor, in6,    RLine,          sensorLineFollower)
#pragma config(Sensor, in7,    LLine,          sensorLineFollower)
#pragma config(Sensor, in8,    Gyro,           sensorGyro)
#pragma config(Sensor, dgtl1,  LauncherSet,    sensorTouch)
#pragma config(Sensor, dgtl2,  AngleSet,       sensorTouch)
#pragma config(Sensor, dgtl3,  Green1,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl4,  Green2,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl5,  Green3,         sensorLEDtoVCC)
#pragma config(Sensor, dgtl6,  Red,            sensorLEDtoVCC)
#pragma config(Sensor, dgtl7,  BallFinder1,    sensorSONAR_cm)
#pragma config(Sensor, dgtl9,  BallFinder2,    sensorSONAR_cm)
#pragma config(Motor,  port1,           Intake,        tmotorVex393_HBridge, openLoop, reversed)
#pragma config(Motor,  port2,           Out1,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RFBase,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           LFBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           Angle,         tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port6,           Out2,          tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RBBase,        tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           LBBase,        tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           AutoLoader,    tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          Elevator,      tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

//VRC Specific pragmas below
#pragma platform(VEX)
#pragma competitionControl(Competition)
#pragma autonomousDuration(20)
#pragma userControlDuration(120)
#include "Vex_Competition_Includes.c"
//VRC Specific pragmas above

#define X_Joy vexRT[Ch4]
#define Y_Joy vexRT[Ch3]
#define rot_Joy vexRT[Ch1]
#define inBtn vexRT[Btn6U]
#define outBtn vexRT[Btn6D]
#define intakeModifierBtn vexRT[Btn5D]
#define outtakeModifierBtn vexRT[Btn5U]
#define launchFast vexRT[Btn8R]
#define launchSlow vexRT[Btn8L]
#define angleUpBtn vexRT[Btn7U]
#define angleDownBtn vexRT[Btn7D]
#define angleLongBtn vexRT[Btn8D]
#define angleShortBtn vexRT[Btn8U]
#define overrideBtn vexRT[Btn7R]
#define toggleSlowBtn vexRT[Btn7L]

int Ball_Count = 0;
int emergenStop = false;

int Auton_Drive_Array[4]; //Arrays that are used during autonomous in a manner similar to the motor array, contains: X, Y, Rot, and Duration
int Auton_Aim_Array[2]; //Contains: Absolute and Adjust
int Auton_Launch_Array[2]; //Contains: Ball Count and Adjust
int Auton_Intake_Array[1]; //Contains: Direction

#include "CONSTANTS.h"
#include "General_Functions.h"
#include "Robot_Functions.h"
#include "Always_Tasks.h"
#include "Autonomous_Tasks.h"
#include "DriverControl_Tasks.h"

#define pew LauncherControl(1)

#include "Autonomous_Skills_Routines.h"

//Predefined construct
void pre_auton()
{
	bStopTasksBetweenModes = true;
	SensorType[in4] = sensorNone; //Reset gyroscope at beginning of program
	wait1Msec(1000);
	SensorType[in4] = sensorGyro;
	wait1Msec(2000);
}

//Predefined construct
task autonomous
{
	startTask(Auton_Aim);
	startTask(Auton_Drive);
	startTask(Auton_Intaking);
	startTask(Auton_Launch);
	string routineName = "ProgSkills1";
	startRoutine(routineName);
}

//Predefined construct
task usercontrol()
{
	Always();
	startTask(Drive);
	startTask(Intaking);
	startTask(Launch);
	startTask(Aim);
	startTask(EmergencyOverride);
	while (true)
	{
		EndTimeSlice();

	}
}
